config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :missions
  resources :teams
  resources :superheros
  resources :users, only: [:show, :new, :create]
  resources :sessions, only: [:new, :create]
  delete '/session', to: 'sessions#destroy', as: 'logout'
  get '/sessions/new', to: 'sessions#new', as: 'login'
  root 'pages#main'
  get 'pages/options', to: 'pages#options', as: 'options'
end

app/models/superhero.rb
class Superhero < ActiveRecord::Base
    has_many :recruits
    has_many :teams, through: :recruits
    has_many :operations, through: :teams
    has_many :missions, through: :operations

    validates :name, presence: true
    validates :name, uniqueness: true
    validates :description, presence: true

    

end

app/controllers/superheros_controller.rb
class SuperherosController < ApplicationController
    before_action :authorize!, only: [:new, :create, :edit, :update, :destroy]
    before_action :superhero_get!, only: [:show, :edit, :update, :destroy]

    def index
        if params[:name]
            create_superhero_from_api(params[:name])
        end
        @superheros = Superhero.all
    end

    def show
    end

    def new
        @superheros = superhero_starts_with(params[:search])
        @superhero = Superhero.new
    end

    def create
        p superhero = create_superhero_from_api(params[:name])
        if superhero.valid?
            superhero.save
            redirect_to superhero
        else
            flash[:message] = superhero.errors.full_messages
            redirect_to new_superhero_path
        end
    end

    def edit
    
    end

    def update
        superhero = @superhero.update(params.require(:superhero).permit(:name, :description, :imgurl))
        if superhero.valid?
            redirect_to supehero_path(@superhero)
        else
            flash[:message] = superhero.errors.full_messages
            redirect_to edit_supehero_path(@superhero)
        end
    end

    def destroy
        @superhero.destroy
        redirect_to superheros_path
    end
    private

    def superhero_params
        params.require(:superhero).permit(:name, :description, :imgurl, :search)
    end

    def superhero_get!
        @superhero = Superhero.find_by(id: params[:id])
    end
end

app/views/superheros/edit.html.erb
<h1>We need a superhero to save the day!</h1>
<em>Edit the form to update this superhero</em>

<div class="flash-messages">
  <% if flash[:message]%>
    <% flash[:message].each do |msg| %>
      <h3><em><%= msg %></em></h3>
    <% end %>
  <% end %>
</div>

<%= form_with model: @superhero do |f| %>
  <p><%= f.label "Superhero Name:" %>
  <%= f.text_field :name %></p>
  <p><%= f.label "Please enter an image url:" %>
  <%= f.text_field :imgurl %></p>
  <p><%= f.label "Write a description:" %></p>
  <p><%= f.text_area :description, cols: 100 %></p>
  <%= f.submit %>
<% end %>

<p><%= link_to "Delete Superhero", @superhero, data: { confirm: "Are you sure?" }, :method => :delete %></p>

app/views/superheros/index.html.erb
<h1>Superheroes</h1>

<ul>
  <% @superheros.each do |superhero| %>
    <li>
      <%= image_tag(superhero.imgurl, height: '100' ) %><%= link_to superhero.name, superhero %>
    </li>
  <% end %>
</ul>

<% if logged_in? %>
    <p><%= link_to "Click Here", new_superhero_path %> to create a new superhero</p>
<% end %>

app/views/superheros/new.html.erb
<h1>We need a superhero to save the day!</h1>
<em>Fill out the form to create a new superhero</em>



<h3>Search the Official Marvel Database for you Hero of Choice:</h3>
    <%= form_tag(new_superhero_path, method: :get) do %>
        <%= text_field_tag(:search, params[:search]) %>
        <%= submit_tag ("Enter the first letters of a Marvel Character's name") %>
    <% end %>

    <% if @superheros %>
        <h4>Click the hero below to create your hero in this database</h4>
        <% @superheros.each do |superhero| %>
        <p><%= link_to superhero, superheros_path( name: superhero), method: :post %></p>
            <p><%#= superhero %></p>
        <% end %>
    <% end %>

app/views/superheros/show.html.erb
<img src="<%= @superhero.imgurl %>" >
<h1><%= @superhero.name %></h1>
<h2>Description:</h2>
<% if @superhero.description == "" %>
    <p>Sorry, no description provided by Marvel, please log in to add your own</p>
<% else %>
    <p><%= @superhero.description %></p>
<% end %>

<% unless @superhero.teams == [] %>
  <h3>Teams:</h3>
  <ul>
    <% @superhero.teams.each do |team| %>
      <li><%= link_to team.name, team %></li>
    <% end %>
  </ul>
<% end %>

<% unless @superhero.missions == [] %>
  <h3>Missions:</h3>
  <ul>
    <% @superhero.missions.each do |mission| %>
      <li><%= link_to mission.name, mission %></li>
    <% end %>
  </ul>
<% end %>

<% if logged_in? %>
    <p><%= link_to "Edit or Delete Superhero", edit_superhero_path(@superhero) %></p>
<% else %>
    <p> Please Log In if you would like to edit this superhero </p>
<% end %>

<p><%= link_to "Back to the Superhero SuperList", superheros_path %>